#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.nssf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-nssf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  nssfcfg.yaml: |
    info:
      version: 1.0.2
      description: NSSF initial local configuration

    configuration:
      serviceNameList:
        {{- .configuration.serviceNameList | nindent 8 }}

      sbi:
        scheme: {{ $.Values.global.sbi.scheme }}
        registerIPv4: {{ include "free5gc-nssf.fullname" $ }}-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .service.port }}
        tls:
          key: cert/nssf.key
          pem: cert/nssf.pem

      nrfUri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}

      nsiList:
        - snssai:
            sst: 1
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 10
        - snssai:
            sst: 1
            sd: 1
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 11
        - snssai:
            sst: 1
            sd: 2
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 12
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 12
        - snssai:
            sst: 1
            sd: 3
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 13
        - snssai:
            sst: 2
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 20
        - snssai:
            sst: 2
            sd: 1
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 21
        - snssai:
            sst: 1
            sd: 010203
          nsiInformationList:
            - nrfId: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}/nnrf-nfm/v1/nf-instances
              nsiId: 22
      amfSetList:
        - amfSetId: 1
          amfList:
            - ffa2e8d7-3275-49c7-8631-6af1df1d9d26
            - 0e8831c3-6286-4689-ab27-1e2161e15cb1
            - a1fba9ba-2e39-4e22-9c74-f749da571d0d
          nrfAmfSet: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:8081/nnrf-nfm/v1/nf-instances
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
                - sst: 2
                  sd: 1
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33457
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
        - amfSetId: 2
          nrfAmfSet: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:8084/nnrf-nfm/v1/nf-instances
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 3
                - sst: 2
                  sd: 1
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33458
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 2

      {{- .configuration.configuration | nindent 6 }}

    logger:
      {{- toYaml .configuration.logger | nindent 6 }}

{{- end }}
