#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v2
name: free5gcN3iwf
description: A Helm chart to deploy the n3iwf function of free5gc
version: 0.1.1
appVersion: v3.0.5
dependencies:
- name: networks5g
  condition: createNetworks
icon: https://camo.githubusercontent.com/915dcf8299b3d2bfe2b2693c5401916cb31e31fb690a73e7da327808000efa37/68747470733a2f2f666f72756d2e667265653567632e6f72672f75706c6f6164732f64656661756c742f6f726967696e616c2f31582f333234363935626663363438316264353536633131303138663238333430383663663565633634352e706e67
maintainers:
  - email: abderaouf.khichane@orange.com
    name: Abderaouf KHICHANE
  - email: ilhem.fajjari@orange.com
    name: Ilhem FAJJARI
  - email: ayoub.bousselmi@orange.com
    name: Ayoub BOUSSELMI
