#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.nrf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-nrf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-nrf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-nrf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-nrf.nrfAnnotations" $ | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/nrf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-nrf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-mongo
        {{- with $.Values.initcontainers.busybox }}
        image: {{ .image }}:{{ .tag }}
        {{- end }}
        env:
        - name: DEPENDENCIES
          {{- with $.Values.mongodb.service }}
          value: {{ .name }}:{{ .port }}
          {{- end }}
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the MongoDB; sleep 2; done;"]
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - containerPort: {{ $.Values.global.nrf.service.port }}
        command: ["./nrf"]
        args: ["-c", "../config/nrfcfg.yaml"]
        env:
          - name: DB_URI
            value: mongodb://{{ $.Values.mongodb.service.name }}/free5gc
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ include "free5gc-nrf.fullname" $ }}-volume
        resources:
            {{- toYaml .resources | nindent 12 }}
        readinessProbe:
          initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
          failureThreshold:  {{ .readinessProbe.failureThreshold }}
          successThreshold: {{ .readinessProbe.successThreshold }}
          httpGet:
            scheme: {{ $.Values.global.sbi.scheme | quote | upper }}
            port: {{ $.Values.global.nrf.service.port }}
        livenessProbe:
          initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .livenessProbe.failureThreshold }}
          successThreshold: {{ .livenessProbe.successThreshold }}
          httpGet:
            scheme: {{ $.Values.global.sbi.scheme | quote | upper }}
            port: {{ $.Values.global.nrf.service.port }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "free5gc-nrf.fullname" $ }}-volume
        projected:
          sources:
          - configMap:
              name: {{ include "free5gc-nrf.fullname" $ }}-configmap
{{- end }}
