#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.free5gc.configmap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.free5gc.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  free5GC.yaml: |
    db_uri: mongodb://{{ .Values.mongodb.service.name }}/free5GC

    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #info
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: info
        ReportCaller: true
      SMF:
        debugLevel: info
        ReportCaller: true
      UDR:
        debugLevel: info
        ReportCaller: true
      UDM:
        debugLevel: info
        ReportCaller: true
      NRF:
        debugLevel: info
        ReportCaller: true
      PCF:
        debugLevel: info
        ReportCaller: true
      AUSF:
        debugLevel: info
        ReportCaller: true
      N3IWF:
        debugLevel: info
        ReportCaller: true
    # library
      NAS:
        debugLevel: info
        ReportCaller: true
      FSM:
        debugLevel: info
        ReportCaller: true
      NGAP:
        debugLevel: info
        ReportCaller: true
      NamfComm:
        debugLevel: info
        ReportCaller: true
      NamfEventExposure:
        debugLevel: info
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: info
        ReportCaller: true
      NudrDataRepository:
        debugLevel: info
        ReportCaller: true
      OpenApi:
        debugLevel: info
        ReportCaller: true
      Aper:
        debugLevel: info
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: info
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: info
        ReportCaller: true
{{- end }}
