{{- if .Values.ue.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ue.configmap.name }}
  labels:
    app: {{ .Values.projectName }}
    component: {{ .Values.ue.name }}
data:
  ue-config.yaml: |
{{- if eq .Values.which5gCore "free5gc" }}
    # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
    supi: 'imsi-208930000000003'
    # Mobile Country Code value
    mcc: '208'
    # Mobile Network Code value (2 or 3 digits)
    mnc: '93'
    
    # Permanent subscription key
    key: '8baf473f2f8fd09487cccbd7097c6862'
    # Operator code (OP or OPC) of the UE
    op: '8e27b6af0e692e750f32667a3b14605d'
    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OP'
    # Authentication Management Field (AMF) value
    amf: '8000'
    # IMEI number of the device. It is used if no SUPI is provided
    imei: '356938035643803'
{{- end }}

{{- if eq .Values.which5gCore "open5gs" }}
    # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
    supi: 'imsi-901700000000003'
    # Mobile Country Code value
    mcc: '901'
    # Mobile Network Code value (2 or 3 digits)
    mnc: '70'
    
    # Permanent subscription key
    key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
    # Operator code (OP or OPC) of the UE
    op: 'E8ED289DEBA952E4283B54E88E6183CA'
    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OP'
    # Authentication Management Field (AMF) value
    amf: '8000'
    # IMEI number of the device. It is used if no SUPI is provided
    imei: '356938035643803'
{{- end }}
    
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - {{ .Values.gnb.service.name }}
    
    # Initial PDU sessions to be established
    sessions:
      - type: 'IPv4'
        apn: '{{ .Values.global.datanetworks.dn1 }}'
        slice:
          sst: 1
          sd: 0x010203
    
    # List of requested S-NSSAIs by this UE
    slices:
      - sst: 1
        sd: 0x010203
    
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true

{{- end }}
