#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021[2021] Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at licenseurlgokoch
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components on top of Kubernetes
#

{{- if .Values.ue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.ue.name }}
  labels:
    app: {{ .Values.projectName }}
    component: {{ .Values.ue.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
      component: {{ .Values.ue.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
        component: {{ .Values.ue.name }}
    spec:
      containers:
      - image: {{ .Values.global.image.registry }}/{{ .Values.ue.image.name }}:{{ .Values.ue.image.tag }}
        name: {{ .Values.ue.name }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["{{ .Values.ue.volume.mount }}/wrapper.sh"]
        volumeMounts:
        - mountPath: {{ .Values.ue.volume.mount }}
          name: {{ .Values.ue.volume.name }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "120m"
          limits:
            memory: "128Mi"
            cpu: "120m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: {{ .Values.ue.volume.name }}
        configMap:
          name: {{ .Values.ue.configmap.name }}
          items:
          - key: ue-config.yaml
            path: ue-config.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0755

{{- end }}
