#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if and .Values.global.upf.service.pfcp.enabled (eq .Values.global.userPlaneArchitecture "ulcl") }}
{{- if and .Values.global.multiCluster }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.upf1.service.pfcp.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.upf1.name }}
spec:
  type: {{ .Values.global.upf.service.pfcp.type }}
  ports:
    - name: n4
      port: {{ .Values.global.upf.service.pfcp.port }}
      targetPort: {{ .Values.global.upf1.service.pfcp.nodeport }}
      protocol: {{ .Values.global.upf.service.pfcp.protocol }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.global.upf1.service.pfcp.name }}
subsets:
  - addresses:
      - ip: {{ .Values.global.upClusterIP }}
    ports:
      - name: n4
        port: {{ .Values.global.upf1.service.pfcp.nodeport }}
        protocol: {{ .Values.global.upf.service.pfcp.protocol }}
{{- end }}
{{- end }}

