#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.ovn4nfv.enabled }}
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: {{ .Values.ovn4nfv.n6network.name }}
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - subnet: {{ .Values.n6network.subnetIP }}/{{ .Values.n6network.cidr }}
    name: subnet1
    gateway: {{ .Values.n6network.gatewayIP }}/{{ .Values.n6network.cidr }}
{{- end }}
