#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.nrf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open5gs-nrf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "open5gs-nrf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open5gs-nrf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "open5gs-nrf.nrfAnnotations" $ | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/nrf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "open5gs-nrf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}

      # initContainers:
      # - name: wait-mongo
      #   {{- with $.Values.initcontainers.busybox }}
      #   image: {{ .image }}:{{ .tag }}
      #   {{- end }}
      #   env:
      #   - name: DEPENDENCIES
      #     {{- with $.Values.mongodb.service }}
      #     value: {{ .name }}:{{ .port }}
      #     {{- end }}
      #   command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the MongoDB; sleep 2; done;"]

      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - containerPort: {{ $.Values.global.nrf.service.port }}
          name: {{ .name }}
        command: ["./open5gs-nrfd"]
        args: ["-c", "{{ .volume.mount }}/etc/nrf.yaml"]
        volumeMounts:
        - mountPath: {{ .volume.mount }}/etc
          name: {{ include "open5gs-nrf.fullname" $ }}-volume
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "open5gs-nrf.fullname" $ }}-volume
        projected:
          sources:
          - configMap:
              name: {{ include "open5gs-nrf.fullname" $ }}-configmap
{{- end }}
