#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
{{- with .Values.upfb }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  upfcfg.yaml: |
    version: 1.0.3
    description: UPF initial local configuration

    # The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
    pfcp:
      addr: {{ .n4if.ipAddress }}   # IP addr for listening
      nodeID: {{ .n4if.ipAddress }} # External IP or FQDN can be reached
      retransTimeout: 1s # retransmission timeout
      maxRetrans: 3 # the max number of retransmission

    gtpu:
      forwarder: gtp5g
      # The IP list of the N3/N9 interfaces on this UPF
      # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
      ifList:
        - addr: {{ .n3if.ipAddress }}
          type: N3
        - addr: {{ .n9if.ipAddress }}
          type: N9
          # name: upf.5gc.nctu.me
          # ifname: gtpif

    {{- toYaml .configuration | nindent 4 }}

  wrapper.sh: |
    #!/bin/sh

    iptables -A FORWARD -j ACCEPT
    iptables -t nat -A POSTROUTING -s {{ $.Values.global.uesubnet }} -o n6 -j MASQUERADE  # Allow routing traffic comming from the UE SUBNET to the interface N6
    iptables -t nat -A POSTROUTING -o n9 -j MASQUERADE
    iptables -t nat -A POSTROUTING -o n3 -j MASQUERADE

    {{- if $.Values.upfb.configmap.wrapperAdditionalCommands }}
    {{- $.Values.upfb.configmap.wrapperAdditionalCommands | toYaml | indent 2 }}
    {{- end }}

    /free5gc/upf/upf -c {{ .volume.mount }}/upfcfg.yaml

{{- end }}
{{- end }}
