#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
{{- with .Values.upf1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  upfcfg.yaml: |
    version: 1.0.3
    description: UPF initial local configuration

    # The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
    pfcp:
      addr: {{ .n4if.ipAddress }}   # IP addr for listening
      nodeID: {{ .n4if.ipAddress }} # External IP or FQDN can be reached
      retransTimeout: 1s # retransmission timeout
      maxRetrans: 3 # the max number of retransmission

    gtpu:
      forwarder: gtp5g
      # The IP list of the N3/N9 interfaces on this UPF
      # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
      ifList:
        - addr: {{ .n9if.ipAddress }}
          type: N9
          # name: upf.5gc.nctu.me
          # ifname: gtpif

    {{- toYaml .configuration | nindent 4 }}

  wrapper.sh: |
    #!/bin/sh

    ### Implement networking rules
    iptables -A FORWARD -j ACCEPT
    iptables -t nat -A POSTROUTING -s {{ $.Values.global.uesubnet }} -o n6 -j MASQUERADE  # route traffic comming from the UE SUBNET to the interface N6
    echo "1200 n6if" >> /etc/iproute2/rt_tables # create a routing table for the interface N6
    ip rule add from {{ $.Values.global.uesubnet }} table n6if   # use the created ip table to route the traffic comming from the UE SUBNET
    ip route add default via {{ $.Values.global.n6network.gatewayIP }} dev n6 table n6if  # add a default route in the created table so that all UEs will use this gateway for external communications (target IP not in the Data Network attached to the interface N6) and then the Data Network will manage to route the traffic

    /free5gc/upf/upf -c {{ .volume.mount }}/upfcfg.yaml

{{- end }}
{{- end }}
