#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
{{- with .Values.upf1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-upf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-upf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-upf.upf1Annotations" $ | nindent 8 }}
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "{{ $.Values.global.n9network.name }}-{{ include "free5gc-upf.fullname" $ }}",
              "interface": "n9",
              "ips": [ "{{ .n9if.ipAddress }}/{{ $.Values.global.n9network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n9network.gatewayIP }}" ]
            },
            { "name": "{{ $.Values.global.n6network.name }}-{{ include "free5gc-upf.fullname" $ }}",
              "interface": "n6",
              "ips": [ "{{ .n6if.ipAddress }}/{{ $.Values.global.n6network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n6network.gatewayIP }}" ]
            },
            { "name": "{{ $.Values.global.n4network.name }}-{{ include "free5gc-upf.fullname" $ }}",
              "interface": "n4",
              "ips": [ "{{ .n4if.ipAddress }}/{{ $.Values.global.n4network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n4network.gatewayIP }}" ]
            }
            ]'
        checksum/config: {{ include (print $.Template.BasePath "/upf1/upf1-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-upf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - name: n4
          containerPort: 8805
          protocol: UDP
        command: ["{{ .volume.mount }}/wrapper.sh"]
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-volume
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-volume
        projected:
          sources:
          - configMap:
              name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-configmap
              items:
              - key: upfcfg.yaml
                path: upfcfg.yaml
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0777
{{- end }}
{{- end }}
