#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if and .Values.global.amf.service.ngap.enabled }}
{{- if and .Values.global.multiCluster }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.amf.service.ngap.name }}
  labels:
    project: {{ .Values.global.projectName }}
spec:
  type: {{ .Values.global.amf.service.ngap.type }}
  ports:
    - name: n2
      port: {{ .Values.global.amf.service.ngap.port }}
      targetPort: {{ .Values.global.amf.service.ngap.nodeport }}
      protocol: {{ .Values.global.amf.service.ngap.protocol }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.global.amf.service.ngap.name }}
subsets:
  - addresses:
      - ip: {{ .Values.global.cpClusterIP }}
    ports:
      - name: n2
        port: {{ .Values.global.amf.service.ngap.nodeport }}
        protocol: {{ .Values.global.amf.service.ngap.protocol }}
{{- end }}
{{- end }}
