#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.udr }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-udr.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  udrcfg.yaml: |
    info:
      version: 1.0.1
      description: UDR initial local configuration

    configuration:
      sbi:
        scheme: {{ $.Values.global.sbi.scheme }}
        registerIPv4: {{ include "free5gc-udr.fullname" $ }}-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .service.port }}
        tls:
          key: config/TLS/udr.key
          pem: config/TLS/udr.pem

      mongodb:
        name: free5gc
        url: mongodb://{{ $.Values.mongodb.service.name }}:{{ $.Values.mongodb.service.port }}

      nrfUri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}

    logger:
      {{- toYaml .configuration.logger | nindent 6 }}

{{- end }}
