#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.amf }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-amf.fullname" $ }}-service
  labels:
    {{- include "free5gc-amf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-amf.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}

{{- if $.Values.isNgapNeeded }}
{{- if $.Values.global.amf.service.ngap.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs-amf.fullname" $ }}-{{ $.Values.global.amf.service.ngap.name }}
  labels:
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ $.Values.global.amf.service.ngap.type }}
  ports:
    - name: n2
      port: {{ $.Values.global.amf.service.ngap.port }}
      nodePort: {{ $.Values.global.amf.service.ngap.nodeport }}
      protocol: {{ $.Values.global.amf.service.ngap.protocol }}
  selector:
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
{{- end }}
{{- end }}

{{- end }}
